name: book-management-system-api

on: 
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'build.gradle'
      - 'Dockerfile'
    branches: [ main ]
    
env:
  NAME: qudtns1223
  REPO: rmsoft-bookmanagement-api
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Build with Gradle
      run: ./gradlew build -Pjasypt.encryptor.password=${{secrets.JASYPT_ENCRYPTOR_PASSWORD}}
        
    - name: Login to DockerHub 
      uses: docker/login-action@v1 
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}} 
        password: ${{secrets.DOCKERHUB_TOKEN}}
        
    - name: Docker Image Build and push
      uses: docker/build-push-action@v2 
      with:
        context: .
        file: ./Dockerfile 
        push: true
        tags: ${{env.NAME}}/${{env.REPO}}:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, api-deploy ] 
    steps:
    
      - name: deploy run 
        run: |
          sh /home/ubuntu/run.sh 
